name: "Build"
on:
  pull_request:
  push:
    branches: [ "master" ]
  workflow_call:

jobs:
  build-target:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: henryouly
        # If you chose signing key for write access
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 10
        run_install: false
    - uses: actions/setup-node@v5 # Uses the setup-node action
      with:
        node-version: 22
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm -C ./frontend install
    - name: Build webapp
      run: pnpm -C ./frontend run build
    - name: Build rust app
      run: ./misc/utils.sh build-target-nix x86_64
    - name: Tar files
      run: tar -cvf sentryshot-x86_64.tar build/x86_64
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: sentryshot-x86_64.tar
