name: Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build-app:
    uses: ./.github/workflows/build.yml

  build-and-push:
    runs-on: ubuntu-latest
    needs: build-app
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Download libusb dependency
      run: |
        ./misc/utils.sh download-debian-libusb

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./misc/Dockerfile
        push: true
        tags: henryouly/sentryshot:latest
